steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    ['compute', 'instance-templates', 'create', 'web-template-$BUILD_ID',
     '--metadata-from-file', 'startup-script=startup.sh',
     '--machine-type=e2-micro', '--tags=http-server']

- name: 'gcr.io/cloud-builders/gcloud'
  args:
    ['compute', 'instance-groups', 'managed', 'rolling-action', 'start-update',
     'web-1-mig', '--version', 'template=web-template-$BUILD_ID',
     '--zone=us-central1-a']

# Required if using build.service_account
logging: CLOUD_LOGGING_ONLY
