options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _ENV: "green"        # blue or green
  _VERSION: "v1"       # version tag

steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t', 'us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:${_ENV}-${_VERSION}-$BUILD_ID',
      '.'
    ]

# Step 2: Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:${_ENV}-${_VERSION}-$BUILD_ID'
    ]

# Step 3: Create instance template for the environment (unique)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Creating instance template for ${_ENV}"
      gcloud beta compute instance-templates create-with-container web-template-${_ENV}-${_VERSION}-$BUILD_ID \
        --machine-type=e2-small \
        --container-image=us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:${_ENV}-${_VERSION}-$BUILD_ID \
        --tags=http-server \
        --quiet

# Step 4: Update the MIG for the environment (rolling update)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Updating MIG for ${_ENV}"
      gcloud compute instance-groups managed rolling-action start-update web-${_ENV}-mig \
        --version template=web-template-${_ENV}-${_VERSION}-$BUILD_ID \
        --zone=us-central1-a \
        --max-surge=1 \
        --max-unavailable=1 \
        --type=proactive \
        --quiet

# Step 5: Switch traffic to the new environment (manual or automated)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Switching LB traffic to ${_ENV}-backend"
      gcloud compute backend-services update web-lb-backend \
        --global \
        --set-backends=group=web-${_ENV}-mig,group-zone=us-central1-a
