options:
  logging: CLOUD_LOGGING_ONLY

steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    ['build', '-t', 'us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:$BUILD_ID', '.']

# Step 2: Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    ['push', 'us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:$BUILD_ID']

# Step 3: Create instance template
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Creating instance template web-template-$BUILD_ID..."
      gcloud beta compute instance-templates create-with-container web-template-$BUILD_ID \
        --machine-type=e2-small \
        --container-image=us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:$BUILD_ID \
        --tags=http-server \
        --quiet

# Step 4: Blue-Green deployment entirely inside Bash
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Variables inside the Bash script
      GREEN_MIG="web-green-$BUILD_ID"
      OLD_MIG="web-1-mig"
      LB_BACKEND="web-lb-backend"

      echo "Creating Green MIG $GREEN_MIG..."
      gcloud compute instance-groups managed create "$GREEN_MIG" \
          --base-instance-name web \
          --size 2 \
          --template web-template-$BUILD_ID \
          --zone us-central1-a \
          --health-check web-mig-hc \
          --initial-delay 30 \
          --quiet

      echo "Waiting for Green MIG instances to be healthy..."
      gcloud compute instance-groups managed wait-until-stable "$GREEN_MIG" \
          --zone us-central1-a

      echo "Switching LB backend to Green MIG only..."
      gcloud compute backend-services update "$LB_BACKEND" \
          --global \
          --instance-group "$GREEN_MIG" \
          --instance-group-zone us-central1-a \
          --quiet

      echo "Removing old MIG from LB..."
      gcloud compute backend-services update "$LB_BACKEND" \
          --global \
          --remove-instance-groups "$OLD_MIG" \
          --instance-group-zone us-central1-a \
          --quiet

      echo "Deleting old MIG $OLD_MIG..."
      gcloud compute instance-groups managed delete "$OLD_MIG" \
          --zone us-central1-a \
          --quiet

images:
  - 'us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:$BUILD_ID'
