options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _ENV: "green"        # blue or green
  _VERSION: "v1"       # version tag

steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t', 'us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:${_ENV}-${_VERSION}-$BUILD_ID',
      '.'
    ]

# Step 2: Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'push',
      'us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:${_ENV}-${_VERSION}-$BUILD_ID'
    ]

# Step 3: Create instance template for the environment (unique)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Creating instance template for ${_ENV}"
      gcloud beta compute instance-templates create-with-container web-template-${_ENV}-${_VERSION}-$BUILD_ID \
        --machine-type=e2-small \
        --container-image=us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:${_ENV}-${_VERSION}-$BUILD_ID \
        --tags=http-server \
        --quiet

# Step 4: Update the MIG for the environment (rolling update)
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Updating MIG for ${_ENV}"
      gcloud compute instance-groups managed rolling-action start-update web-${_ENV}-mig \
        --version template=web-template-${_ENV}-${_VERSION}-$BUILD_ID \
        --zone=us-central1-a \
        --max-surge=1 \
        --max-unavailable=1 \
        --type=proactive \
        --quiet

# Step 5: Wait for backend to become healthy
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Waiting for ${_ENV} backend to become healthy..."
      BACKEND="${_ENV}-backend"
      while true; do
        HEALTHY=$(gcloud compute backend-services get-health $BACKEND --global --format="value(healthStatus[].healthState)" | grep -c HEALTHY)
        if [ "$HEALTHY" -ge 1 ]; then
          echo "${_ENV} backend is healthy ✅"
          break
        fi
        echo "Not healthy yet, waiting 5s..."
        sleep 5
      done

# Step 6: Switch traffic using shell script
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      if [ "${_ENV}" == "green" ]; then
        echo "Switching LB traffic to GREEN environment"
        bash switch-to-green.sh
      else
        echo "Switching LB traffic to BLUE environment"
        bash switch-to-blue.sh
      fi
