steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:$BUILD_ID',
    '.'
  ]

# Step 2: Push Docker image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push',
    'us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:$BUILD_ID'
  ]

# Step 3: Create new instance template with container
- name: 'gcr.io/cloud-builders/gcloud:beta'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Creating instance template web-template-$BUILD_ID"
      gcloud beta compute instance-templates create web-template-$BUILD_ID \
        --machine-type=e2-small \
        --image-family=cos-stable \
        --image-project=cos-cloud \
        --container-image=us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:$BUILD_ID \
        --tags=http-server \
        --quiet

# Step 4: Roll update the managed instance group
- name: 'gcr.io/cloud-builders/gcloud:beta'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Updating MIG web-1-mig with new template"
      gcloud compute instance-groups managed rolling-action start-update web-1-mig \
        --version template=web-template-$BUILD_ID \
        --zone=us-central1-a \
        --quiet

images:
- 'us-central1-docker.pkg.dev/singular-object-464504-a3/artifact-repo/static-web:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
